application:
  name: configurationservice

management:
  security:
    enabled: false
spring:
  profiles.active: development

server:
  port: 8081
  contextPath: /config
---
spring:
  profiles: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaeedAlbarhami/config/

---
spring:
  profiles: production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaeedAlbarhami/config/

